# Generated by Django 2.1 on 2020-02-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200207_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('ty_pe', models.CharField(blank=True, max_length=20, null=True)),
                ('keywords', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=180)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
