# Generated by Django 2.1 on 2020-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200210_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='products/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='products/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='products/image/'),
        ),
    ]
